# Generated by Django 4.2.6 on 2023-11-26 11:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dersproje', '0003_quips'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quips',
            new_name='Quip',
        ),
    ]
