# Generated by Django 4.2.6 on 2023-12-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersproje', '0004_rename_quips_quip'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
