# Generated by Django 4.2.6 on 2023-12-27 03:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dersproje', '0005_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quip',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='quip_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
